### ISSUE TITLE
Fix to do in Backend

### ISSUE THREAD

**Issue by gh4m21** [makensonlamour/vwanu#420]
### Task:

- [x] Change payload community-invitation-request from string to an array of string id for guestId
- [x] Add address to users so even if I didn't change state,city,etc... to see them equal to null. Look like you didn't habilitate them.
- [x] When Following a user, iFollow should be true and IsAFollower should be false, but It's the IsAFollower that is true and iFollow still remains false. 
- [x] blog request same data for different id in findOne blog by id, 
- [x] blog have only UserId. It should contain the object of the user.
- [ ] when delete an album, I got the error message: Cannot set property 'UserId' of undefined.
- [x] post on community appeared in timeline
- [x] create a test to fetch users based on location and interest for suggested users.
- [x] Add option kick, ban a member from a community
- [x] add an option to block a user(if it's possible)
- [x] Add an option to demote an administrator to moderator or member without sending an invitation.
- [x] Add in users response, isFollowyou, isIFollow like you did with hasinvitation... and isfriend
- [x] Add Interests in users so I can access the array of interest
- [x] Remove friend request if user decline friend request, and change hasfriendrequest to false, etc...
- [x] Fetch blogs by interest
- [x] fetch blogs by most comments
- [x] fix can't post images, videos or gif without sending postText
- [x] After the user accepts moderators or administrator invitations, he can't fetch all community. Error: {Message: "more than one row returned by a subquery used as an expression"}
- [x] Return as the response when a user visits another profile: pending friend request, and if they are friends.
- [x] Online user
- [x] Add in object pendingInvitation when fetching community: guestId, hostId
- [x] Create a test to fetch list community by most popular( max number of members in community)
- [x] Create a test to fetch list community by the newest
- [x] Create a test to fetch list community by interest
- [x] Create a test to fetch the list community that a user creates.
- [x] create a test to fetch list communities that a user is a member of
- [x]  Add community settings from the database for can invite, can post.
- [x] Add user first name and Last name and comments in last comment when you fetch a list of discussion
- [x] For some unknown reasons, /blogs didn't have as reponse total, limit, skip.... Please investigate and fix for pagination.
- [x] Filter HTML parser by className and style for blogs to have style.
- [x] When I fetch the list of conversations, listMessages, I didn't see total,skip,
